#!/usr/bin/env python3
"""Generate the offline Dart table for the twelve exact month-starting Jie.

The generated values are wall-clock timestamps in Asia/Shanghai from the
locked lunar_python 1.4.8 provider used by liuyao-private.  Keep this script so
the data remains reproducible instead of becoming an unexplained copied table.
"""

from __future__ import annotations

from importlib.metadata import version
from pathlib import Path

from lunar_python import Solar


START_YEAR = 1901
END_YEAR = 2099
TERMS = (
    ("小寒", 1),
    ("立春", 2),
    ("惊蛰", 3),
    ("清明", 4),
    ("立夏", 5),
    ("芒种", 6),
    ("小暑", 7),
    ("立秋", 8),
    ("白露", 9),
    ("寒露", 10),
    ("立冬", 11),
    ("大雪", 12),
)
OUTPUT = (
    Path(__file__).resolve().parents[1]
    / "packages/liuyao_engine/lib/src/exact_jie_terms.dart"
)


def timestamp(year: int, month: int, name: str) -> str:
    table = Solar.fromYmdHms(year, month, 15, 12, 0, 0).getLunar().getJieQiTable()
    value = table[name]
    return (
        f"{value.getYear():04d}{value.getMonth():02d}{value.getDay():02d}"
        f"{value.getHour():02d}{value.getMinute():02d}{value.getSecond():02d}"
    )


def main() -> None:
    provider_version = version("lunar_python")
    if provider_version != "1.4.8":
        raise SystemExit(
            f"lunar_python 1.4.8 required, found {provider_version}; refusing drift"
        )

    rows = [
        "/// Generated by scripts/generate_exact_jie_table.py.",
        "/// Source: lunar_python 1.4.8, Asia/Shanghai wall-clock values.",
        "/// Do not edit this table by hand.",
        "library;",
        "",
        f"const int exactJieStartYear = {START_YEAR};",
        f"const int exactJieEndYear = {END_YEAR};",
        "const String exactJieProviderVersion = '1.4.8';",
        "const String exactJieProviderRevision =",
        "    '000c8a3d74eed098d6256a28fdd51b869324c559';",
        "",
        "const List<String> exactJieNames = [",
        *[f"  '{name}'," for name, _ in TERMS],
        "];",
        "",
        "const List<String> exactJieWallClockRows = [",
    ]
    for year in range(START_YEAR, END_YEAR + 1):
        packed = ",".join(timestamp(year, month, name) for name, month in TERMS)
        rows.append(f"  '{packed}', // {year}")
    rows.extend(["];", ""])
    OUTPUT.write_text("\n".join(rows), encoding="utf-8")


if __name__ == "__main__":
    main()
